### Hello world test
GET http://localhost:9090/hello

### Get all recipes
GET http://localhost:9090/app/recipes

### Post recipe with body
POST http://localhost:9090/app/recipes
Content-Type: application/json

{
  "title": "Rosol",
  "description": "Wrzucic kurczaka i gotowac z przyprawami oraz warzywami",
  "author": {
    "name": "Tomasz Zoladz"
  },
  "ingredients": [
    {
      "name": "Kurczak"
    },
    {
      "name": "Przyprawy"
    },
    {
      "name": "Warzywa"
    }
  ],
  "appliances": [
    {
      "name": "Garnek"
    },
    {
      "name": "Kuchenka"
    },
    {
      "name": "Chochla"
    }
  ]
}

### Patch recipe with title
PATCH http://localhost:9090/app/recipes/title?id=714f7c19-ca02-432c-8622-823b6aa5ace0&title=Śmieszny bigos z warzywkami
