### Hello world test
GET http://localhost:9090/hello

### Get all recipes
GET http://localhost:9090/app/recipes

### Get recipe by ID
GET http://localhost:9090/app/recipes/c70df1a1-945e-4b4f-8ae1-a42f7d295f27

### Post recipe with body
POST http://localhost:9090/app/recipes
Content-Type: application/json

{
  "title": "Salatka",
  "description": "Zmieszac wszystkie skladniki dokladnie",
  "authorId": "40bb900f-91ab-4614-abb9-a642da9c1181",
  "ingredientIds": [],
  "applianceIds": []
}





### Post author with body
POST http://localhost:9090/app/authors
Content-Type: application/json

{
  "name": "Stanisław Nowak"
}

### Get all authors
GET http://localhost:9090/app/authors

### Get author by ID
GET http://localhost:9090/app/authors/5c03d221-701d-42bf-bf66-8361b5bfd933